[build]
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://vabelgian.github.io"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept"
    Access-Control-Allow-Methods = "POST, OPTIONS"
